;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; The selection range of the key is as follows. Please ensure the correct spelling of the string.
; 'fwd':[
;     'Is_dropout', 'Is_causal', 'Is_local', 'Has_alibi', 'Has_attn_mask',
;     'Is_even_MN', 'Is_even_K', 'Is_softcap',
;     'Return_softmax', 'Rowblock_Parallel_Num', 'Merge_attn_mask_ldg',
; ],
; 'bwd':[
;     'Is_dropout', 'Is_causal', 'Is_local', 'Has_alibi', 'Has_attn_mask',
;     'Is_even_MN', 'Is_even_K', 'Is_softcap',
;     'Is_deterministic', 'Is_balance',
; ],
; 'fwd_split':[
;     'Is_causal', 'Is_local', 'Has_alibi','Is_even_MN', 'Is_even_K', 'Is_softcap',
;     'Split', 'AppendKV', 'Is_page_attn'
; ]
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; There are two sections:
; [SpecificValues] for specifying the values of bool switches as true or false, or true, false;
; [DefaultValues]  for specifying the values of bool switches that are not configured.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Example
; [SpecificValues]
; Is_dropout = True
; Is_causal = True,False
; Is_local = False
; Has_alibi = False
; Has_attn_mask = True
; [DefaultValues]
; default_value = False
;

; Generate fullkernels
; Keep the default_value as "True, False" order to don't get unexpeted change
;[SpecificValues]
;
;[DefaultValues]
;default_value =  True, False
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[SpecificValues]

[DefaultValues]
default_value = True, False
