function(_flash_attn_get_dispatch_mn OUT_VAR MACA_ARCH SOURCE_KIND HDIM)
    if("${MACA_ARCH}" STREQUAL "xcore1000")
        if("${SOURCE_KIND}" STREQUAL "fwd")
            if("${HDIM}" STREQUAL "0")
                set(MN_LIST "32x32,64x32,64x64,128x64,128x128")
            elseif("${HDIM}" STREQUAL "32")
                set(MN_LIST "128x128")
            elseif("${HDIM}" STREQUAL "64")
                set(MN_LIST "64x64")
            elseif("${HDIM}" STREQUAL "96")
                set(MN_LIST "128x64")
            elseif("${HDIM}" STREQUAL "128")
                set(MN_LIST "64x64")
            elseif("${HDIM}" STREQUAL "160")
                set(MN_LIST "64x32")
            elseif("${HDIM}" STREQUAL "192")
                set(MN_LIST "64x64,128x64")
            elseif("${HDIM}" STREQUAL "256")
                if(BUILD_WITH_BWD_KERNEL)
                    set(MN_LIST "64x32,64x64")
                else()
                    set(MN_LIST "64x32")
                endif()
            elseif("${HDIM}" STREQUAL "512")
                set(MN_LIST "64x32")
            else()
                set(MN_LIST "")
            endif()
        elseif("${SOURCE_KIND}" STREQUAL "fwd_split")
            if("${HDIM}" STREQUAL "0")
                set(MN_LIST "32x32,64x64")
            elseif("${HDIM}" STREQUAL "512")
                set(MN_LIST "32x32")
            else()
                set(MN_LIST "64x64")
            endif()
        else()
            message(FATAL_ERROR "Unknown ${MACA_ARCH} fwd source kind: ${SOURCE_KIND}")
        endif()
    elseif("${MACA_ARCH}" STREQUAL "xcore1500")
        if("${SOURCE_KIND}" STREQUAL "fwd")
            if("${HDIM}" STREQUAL "0")
                set(MN_LIST "128x64,128x128")
            elseif("${HDIM}" STREQUAL "32")
                set(MN_LIST "128x64,128x128")
            elseif("${HDIM}" STREQUAL "512")
                set(MN_LIST "")
            else()
                set(MN_LIST "128x64")
            endif()
        elseif("${SOURCE_KIND}" STREQUAL "fwd_split")
            if("${HDIM}" STREQUAL "0")
                set(MN_LIST "16x32,64x64,128x64")
            elseif("${HDIM}" STREQUAL "32")
                set(MN_LIST "64x64")
            elseif("${HDIM}" STREQUAL "64")
                set(MN_LIST "128x64")
            elseif("${HDIM}" STREQUAL "96")
                set(MN_LIST "64x64")
            elseif("${HDIM}" STREQUAL "128")
                set(MN_LIST "16x32,128x64")
            elseif("${HDIM}" STREQUAL "160")
                set(MN_LIST "64x64")
            elseif("${HDIM}" STREQUAL "192")
                set(MN_LIST "128x64")
            elseif("${HDIM}" STREQUAL "256")
                set(MN_LIST "128x64")
            else()
                set(MN_LIST "")
            endif()
        else()
            message(FATAL_ERROR "Unknown ${MACA_ARCH} fwd source kind: ${SOURCE_KIND}")
        endif()
    else()
        set(MN_LIST "")
    endif()

    set(${OUT_VAR} "${MN_LIST}" PARENT_SCOPE)
endfunction()

function(_flash_attn_filter_mn_sources SOURCE_VAR MN_LIST LABEL MACA_ARCH)
    if("${MN_LIST}" STREQUAL "")
        return()
    endif()

    string(REPLACE "," ";" FWD_MN_ITEMS "${MN_LIST}")
    set(FWD_MN_REGEX "")
    foreach(FWD_MN_ITEM IN LISTS FWD_MN_ITEMS)
        string(STRIP "${FWD_MN_ITEM}" FWD_MN_ITEM)
        if("${FWD_MN_ITEM}" STREQUAL "")
            continue()
        endif()
        string(TOLOWER "${FWD_MN_ITEM}" FWD_MN_ITEM)
        string(REPLACE "x" "n" FWD_MN_TOKEN "${FWD_MN_ITEM}")
        set(FWD_MN_TOKEN "m${FWD_MN_TOKEN}")
        if("${FWD_MN_REGEX}" STREQUAL "")
            set(FWD_MN_REGEX "_(${FWD_MN_TOKEN}")
        else()
            set(FWD_MN_REGEX "${FWD_MN_REGEX}|${FWD_MN_TOKEN}")
        endif()
    endforeach()

    if("${FWD_MN_REGEX}" STREQUAL "")
        return()
    endif()

    set(FWD_MN_REGEX "${FWD_MN_REGEX})_")
    set(SOURCES ${${SOURCE_VAR}})
    list(FILTER SOURCES INCLUDE REGEX "${FWD_MN_REGEX}")
    set(${SOURCE_VAR} "${SOURCES}" PARENT_SCOPE)
    message(STATUS "Filter ${MACA_ARCH} ${LABEL} kernels by MN_LIST=${MN_LIST}, regex=${FWD_MN_REGEX}")
endfunction()

macro(build_flash_attn_kernel LIB_NAME  MACA_ARCH HDIM DTYPE)

    set(HDIM_FILTER "")
    if(NOT HDIM STREQUAL "0")
        set(HDIM_FILTER ${HDIM})
    endif()

    set(DTYPE_FILTER "*")

    STRING(TOLOWER "${DTYPE}" DTYPE_LOWER)
    if(NOT ${DTYPE_LOWER} STREQUAL "all")
        set(DTYPE_FILTER ${DTYPE_LOWER})
        message(STATUS "DTYPE:${DTYPE}")
    endif()

    set(SRC_FILTER "${HDIM_FILTER}*_${DTYPE_FILTER}_*")

    message(STATUS "SRC_FILTER:${SRC_FILTER}")

    set(SRC_PARENT ${CMAKE_CURRENT_SOURCE_DIR}/tools/generator)
    if(FAST_BUILD)
        set(SRC_PARENT "build_kernel")
    endif()

    file(GLOB FWD_TRAITS_SRC "${SRC_PARENT}/run_flash_template/${MACA_ARCH}/fwd/flash_fwd_hdimqk${SRC_FILTER}.cpp")
    file(GLOB FWD_SPLIT_TRAITS_SRC "${SRC_PARENT}/run_flash_template/${MACA_ARCH}/fwd_split/flash_fwd_splitkv_hdimqk${SRC_FILTER}.cpp")

    file(GLOB FWD_KERNEL_SRC "${SRC_PARENT}/full_kernels/${MACA_ARCH}/fwd/flash_fwd_hdimqk${SRC_FILTER}.cpp")
    file(GLOB FWD_SPLIT_KERNEL_SRC "${SRC_PARENT}/full_kernels/${MACA_ARCH}/fwd_split/flash_fwd_splitkv_hdimqk${SRC_FILTER}.cpp")

    if("${MACA_ARCH}" STREQUAL "xcore1000" OR "${MACA_ARCH}" STREQUAL "xcore1500")
        set(FWD_MN_EFFECTIVE "${FWD_MN_LIST}")
        string(TOUPPER "${FWD_MN_EFFECTIVE}" FWD_MN_EFFECTIVE_UPPER)
        if("${FWD_MN_EFFECTIVE_UPPER}" STREQUAL "DEFAULT")
            _flash_attn_get_dispatch_mn(FWD_MN_EFFECTIVE "${MACA_ARCH}" "fwd" "${HDIM}")
        endif()

        set(FWD_SPLIT_MN_EFFECTIVE "${FWD_SPLIT_MN_LIST}")
        string(TOUPPER "${FWD_SPLIT_MN_EFFECTIVE}" FWD_SPLIT_MN_EFFECTIVE_UPPER)
        if("${FWD_SPLIT_MN_EFFECTIVE_UPPER}" STREQUAL "DEFAULT")
            _flash_attn_get_dispatch_mn(FWD_SPLIT_MN_EFFECTIVE "${MACA_ARCH}" "fwd_split" "${HDIM}")
        endif()

        _flash_attn_filter_mn_sources(FWD_TRAITS_SRC "${FWD_MN_EFFECTIVE}" "fwd traits" "${MACA_ARCH}")
        _flash_attn_filter_mn_sources(FWD_KERNEL_SRC "${FWD_MN_EFFECTIVE}" "fwd full" "${MACA_ARCH}")
        _flash_attn_filter_mn_sources(FWD_SPLIT_TRAITS_SRC "${FWD_SPLIT_MN_EFFECTIVE}" "fwd_split traits" "${MACA_ARCH}")
        _flash_attn_filter_mn_sources(FWD_SPLIT_KERNEL_SRC "${FWD_SPLIT_MN_EFFECTIVE}" "fwd_split full" "${MACA_ARCH}")
    endif()

    if(NOT BUILD_WITH_BWD_KERNEL)
        list(FILTER FWD_KERNEL_SRC EXCLUDE REGEX "_dropout_")
        message(STATUS "Disable dropout fwd kernels because BUILD_WITH_BWD_KERNEL is OFF")
    endif()
    if(NOT FWD_ENABLE_LOCAL)
        list(FILTER FWD_SPLIT_KERNEL_SRC EXCLUDE REGEX "_Is_local")
        message(STATUS "Disable local fwd_split full kernels")
    endif()
    if(NOT FWD_ENABLE_ALIBI)
        list(FILTER FWD_SPLIT_KERNEL_SRC EXCLUDE REGEX "_alibi")
        message(STATUS "Disable alibi fwd_split full kernels")
    endif()
    if(NOT FWD_ENABLE_CAUSAL)
        list(FILTER FWD_SPLIT_KERNEL_SRC EXCLUDE REGEX "_causal")
        message(STATUS "Disable causal fwd_split full kernels")
    endif()

    if(BUILD_WITH_BWD_KERNEL)
        file(GLOB BWD_TRAITS_SRC "${SRC_PARENT}/run_flash_template/${MACA_ARCH}/bwd/flash_bwd_hdimqk${SRC_FILTER}.cpp")
        file(GLOB BWD_KERNEL_SRC "${SRC_PARENT}/full_kernels/${MACA_ARCH}/bwd/flash_bwd_hdimqk${SRC_FILTER}.cpp")
    else()
        set(BWD_TRAITS_SRC "")
        set(BWD_KERNEL_SRC "")
    endif()

    add_library(${LIB_NAME} STATIC
        ${FWD_KERNEL_SRC}
        ${FWD_TRAITS_SRC}
        ${BWD_KERNEL_SRC}
        ${BWD_TRAITS_SRC}
        ${FWD_SPLIT_KERNEL_SRC}
        ${FWD_SPLIT_TRAITS_SRC}
    )
    message (STATUS "lib_name ${LIB_NAME}")

endmacro()

macro(build_flash_attn_host LIB_NAME)
    set(FLASH_ATTN_SRC
        csrc/flash_attn/flash_run/flash_performance_mode.cpp
        csrc/flash_attn/flash_run/flash_launch_parameter.cpp
        csrc/flash_attn/flash_run/run_mha_fwd.cpp
        csrc/flash_attn/utils/print_parameter.cpp
        csrc/common/process_str.cpp
        csrc/common/logger.cpp
    )
    if(BUILD_WITH_BWD_KERNEL)
        list(APPEND FLASH_ATTN_SRC csrc/flash_attn/flash_run/run_mha_bwd.cpp)
    else()
        message(STATUS "Disable backward host sources because BUILD_WITH_BWD_KERNEL is OFF")
    endif()
    add_library(${LIB_NAME} STATIC
        ${FLASH_ATTN_SRC}
    )

endmacro()
